const MATRIX = 'MATRIX_PAGE_';

export const SET_GROUPS = `${MATRIX}SET_GROUPS`;
export const UPDATE_GROUP = `${MATRIX}UPDATE_GROUP`;

export const UPDATE_CURRENT_ITEM = `${MATRIX}UPDATE_CURRENT_ITEM`;
export const UPDATE_OPEN_SKILL = `${MATRIX}UPDATE_OPEN_SKILL`;
export const UPDATE_USERS_LIST = `${MATRIX}UPDATE_USERS_LIST`;
export const UPDATE_SELECTED_USER = `${MATRIX}UPDATE_SELECTED_USER`;
export const UPDATE_SECTION = `${MATRIX}UPDATE_SECTION`;

export const UPDATE_SKILL = `${MATRIX}UPDATE_SKILL`;
export const SET_USER_SKILL = `${MATRIX}SET_USER_SKILL`;

export const UPDATE_USER_SKILLS = `${MATRIX}UPDATE_USER_SKILLS`;
export const UPDATE_USER_SKILL = `${MATRIX}UPDATE_USER_SKILL`;

export const UPDATE_REMOVED_ITEM = `${MATRIX}UPDATE_REMOVED_ITEM`;
export const ADD_COMMENT = `${MATRIX}ADD_COMMENT`;

export const SET_GOD_MODE = `${MATRIX}SET_GOD_MODE`;
